# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c3fbe034491faf7ab5a2174328d6b95c16f260dac929477327f8ea10c1156c6278100f48daa8107699e92ae3730982d6514784072f45d4dde77a2dbc25cc581

test:
  secret_key_base: e50b773be07f5d15d1d15c4c40cc81c68278b134de1660e8347b3e1d513ec6602b74b65dc952711597e5ac02f8973682dc1ffeeac48e430aee1a9cfba0e56e34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
